<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FCG.PaymentsAPI</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>
</Project>
